import { db, Slot, User } from 'astro:db'
import { generateId } from 'lucia'

// https://astro.build/db/seed
export default async function seed() {
  await db.insert(Slot).values([
    { id: generateId(15), week_day: 1, start_hour: 10, end_hour: 11, size: 8 },
    { id: generateId(15), week_day: 1, start_hour: 11, end_hour: 12, size: 4 },
    { id: generateId(15), week_day: 1, start_hour: 12, end_hour: 13, size: 1 },
    { id: generateId(15), week_day: 1, start_hour: 13, end_hour: 14, size: 8 },
    { id: generateId(15), week_day: 1, start_hour: 16, end_hour: 17, size: 4 },
    { id: generateId(15), week_day: 1, start_hour: 17, end_hour: 18, size: 1 },
    { id: generateId(15), week_day: 1, start_hour: 18, end_hour: 19, size: 8 },
    { id: generateId(15), week_day: 1, start_hour: 19, end_hour: 20, size: 4 },
    { id: generateId(15), week_day: 1, start_hour: 20, end_hour: 21, size: 1 },
    { id: generateId(15), week_day: 1, start_hour: 21, end_hour: 22, size: 8 },
    { id: generateId(15), week_day: 2, start_hour: 8, end_hour: 9, size: 4 },
    { id: generateId(15), week_day: 2, start_hour: 9, end_hour: 10, size: 1 },
    { id: generateId(15), week_day: 2, start_hour: 10, end_hour: 11, size: 8 },
    { id: generateId(15), week_day: 2, start_hour: 11, end_hour: 12, size: 4 },
    { id: generateId(15), week_day: 2, start_hour: 12, end_hour: 13, size: 1 },
    { id: generateId(15), week_day: 2, start_hour: 13, end_hour: 14, size: 8 },
    { id: generateId(15), week_day: 2, start_hour: 16, end_hour: 17, size: 4 },
    { id: generateId(15), week_day: 2, start_hour: 17, end_hour: 18, size: 1 },
    { id: generateId(15), week_day: 2, start_hour: 18, end_hour: 19, size: 8 },
    { id: generateId(15), week_day: 2, start_hour: 19, end_hour: 20, size: 4 },
    { id: generateId(15), week_day: 2, start_hour: 20, end_hour: 21, size: 1 },
    { id: generateId(15), week_day: 2, start_hour: 21, end_hour: 22, size: 8 },
    { id: generateId(15), week_day: 3, start_hour: 8, end_hour: 9, size: 4 },
    { id: generateId(15), week_day: 3, start_hour: 9, end_hour: 10, size: 1 },
    { id: generateId(15), week_day: 3, start_hour: 10, end_hour: 11, size: 8 },
    { id: generateId(15), week_day: 3, start_hour: 11, end_hour: 12, size: 4 },
    { id: generateId(15), week_day: 3, start_hour: 12, end_hour: 13, size: 1 },
    { id: generateId(15), week_day: 3, start_hour: 13, end_hour: 14, size: 8 },
    { id: generateId(15), week_day: 3, start_hour: 16, end_hour: 17, size: 4 },
    { id: generateId(15), week_day: 3, start_hour: 17, end_hour: 18, size: 1 },
    { id: generateId(15), week_day: 3, start_hour: 18, end_hour: 19, size: 8 },
    { id: generateId(15), week_day: 3, start_hour: 19, end_hour: 20, size: 4 },
    { id: generateId(15), week_day: 3, start_hour: 20, end_hour: 21, size: 1 },
    { id: generateId(15), week_day: 3, start_hour: 21, end_hour: 22, size: 8 },
    { id: generateId(15), week_day: 4, start_hour: 8, end_hour: 9, size: 4 },
    { id: generateId(15), week_day: 4, start_hour: 9, end_hour: 10, size: 1 },
    { id: generateId(15), week_day: 4, start_hour: 10, end_hour: 11, size: 8 },
    { id: generateId(15), week_day: 4, start_hour: 11, end_hour: 12, size: 4 },
    { id: generateId(15), week_day: 4, start_hour: 12, end_hour: 13, size: 1 },
    { id: generateId(15), week_day: 4, start_hour: 13, end_hour: 14, size: 8 },
    { id: generateId(15), week_day: 4, start_hour: 16, end_hour: 17, size: 4 },
    { id: generateId(15), week_day: 4, start_hour: 17, end_hour: 18, size: 1 },
    { id: generateId(15), week_day: 4, start_hour: 18, end_hour: 19, size: 8 },
    { id: generateId(15), week_day: 4, start_hour: 19, end_hour: 20, size: 4 },
    { id: generateId(15), week_day: 4, start_hour: 20, end_hour: 21, size: 1 },
    { id: generateId(15), week_day: 4, start_hour: 21, end_hour: 22, size: 8 },
    { id: generateId(15), week_day: 5, start_hour: 8, end_hour: 9, size: 4 },
    { id: generateId(15), week_day: 5, start_hour: 9, end_hour: 10, size: 1 },
    { id: generateId(15), week_day: 5, start_hour: 10, end_hour: 11, size: 8 },
    { id: generateId(15), week_day: 5, start_hour: 11, end_hour: 12, size: 4 },
    { id: generateId(15), week_day: 5, start_hour: 12, end_hour: 13, size: 1 },
    { id: generateId(15), week_day: 5, start_hour: 13, end_hour: 14, size: 8 },
    { id: generateId(15), week_day: 5, start_hour: 16, end_hour: 17, size: 4 },
    { id: generateId(15), week_day: 5, start_hour: 17, end_hour: 18, size: 1 },
    { id: generateId(15), week_day: 5, start_hour: 18, end_hour: 19, size: 8 },
    { id: generateId(15), week_day: 5, start_hour: 19, end_hour: 20, size: 4 }
  ])
}
